export { responsiveStateReducer as breakpoint } from 'redux-responsive';
export { default as page } from './page';
export { default as category } from './category';
export { default as packages } from './packages';
export { default as title } from './title';
export { default as panelColor } from './panelColor';
export { default as pageIdent } from './pageIdent';
export { default as typeColor } from './typeColor';
export { default as about } from './about';
